import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'injection.config.dart'; // Will be generated by build_runner

final GetIt injector = GetIt.instance;

@InjectableInit()
void configureDependencies() => injector.init();
